name: Unit tests

on:
  push:
    branches:
      - main
      - next

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Setup PNPM
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.14.2
        run_install: |
          - args: [--shamefully-hoist]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - run: pnpm install
    - run: pnpm build
    - run: pnpm test
    - run: pnpm publish
